### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [millsmcilroy/movie-inventory-crud#1]
Avoid string concatenation for queries you did in your code everywhere ;)

The following post explains the issue: [Invalid query formatting with manual string concatenation and ES6 template strings](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#invalid-query-formatting-with-manual-string-concatenation-and-es6-template-strings)

**Comment by mcilroymills** [comment]
Thanks!

**Comment by vitaly-t** [comment]
You should avoid manual query concatenation completely.

For example, instead of this:

``` js
db.any('SELECT * FROM movies ORDER BY title ' + req.query.title)
```

use this:

``` js
// inserts raw-text variable:
db.any('SELECT * FROM movies ORDER BY title $1^', req.query.title)
```

**Comment by mcilroymills** [comment]
I agree with you in principle, but the way that code is written the query will only run if req.query.title === 'asc' or req.query.title === 'desc', so it should be safe.
